services:

  minivault-db:
    image: postgres:16-alpine
    container_name: minivault-db
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${SPRING_DATASOURCE_USERNAME}
      - POSTGRES_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    ports:
      - "${POSTGRES_DB_PORT}:5432"
    volumes:
      - minivault-db-data:/var/lib/postgresql/data

volumes:
  minivault-db-data:  

